### ISSUE TITLE
Using zclip to copy multiple values with multiple copy buttons?

### ISSUE THREAD

**Issue by samayres1992** [patricklodder/jquery-zclip#8]
Strange issue, flash object fails to initialize on all buttons even though zclip is called for each button. 

Current code: 
<code>
$(document).ready(function(){
$('.copylink').each(function(){
    $(this).zclip({
        path :  '/flash/ZeroClipboard.swf',
           copy: function(){ return $(this).attr('data-copy-shorturl'); },
           afterCopy: function()
           {
               console.log($(this).data('copy-shorturl') + " was copied to clipboard");
           }
    });
});
});
</code>
Example of the buttons being initialized: 

![image 2014-08-05 at 6 24 57 am](https://cloud.githubusercontent.com/assets/990796/3807241/ed3bc486-1c61-11e4-99b3-5150ee6ae4bf.png)

Currently only the first button on the page actually copies it's value to clipboard, any thoughts on what could be the issue? I'm sure whether or not this is simply a coding issue on my behalf or a genuine bug.  Thank you.

**Comment by patricklodder** [comment]
Sorry to be slow on this one. I tried reproducing your findings but I cannot. Are you able to reproduce using something like [jsfiddle](http://jsfiddle.net/) and share? Also, which jquery/flash/browser versions are you using?

This is what worked for me:

``` html
<!DOCTYPE html>
<html>
  <head>
    <title>Multi button test</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="jquery.zclip.js"></script>
    <script>
      $(document).ready(function () { 

       $('.copylink').each(function (k,n) {
          $(this).zclip({
            path: 'ZeroClipboard.swf',
            copy: function () { 
              var val = $(this).attr('data-copy-text'); 
              return val;
            },
            afterCopy: function () { console.log($(this).data('copy-text') + " was copied to clipboard"); }
          });
        });
      });
    </script>
  </head>
  <body>
    <button class="copylink" data-copy-text="button1">copy</button>
    <button class="copylink" data-copy-text="button2">copy</button>
    <button class="copylink" data-copy-text="button3">copy</button>
  </body>
</html>
```

I've tested this with:
- Chrome 36.0.1985.143
- Built-in flash 14.0.0.177
- JQuery 1.11.1

and
- Firefox 31.0
- Flash 11.2.202.400

**Comment by samayres1992** [comment]
Hi Patrick,

Thanks for the reply, I did dig a lot deeper in to the issue and basically just worked out through breakpoints that the values are being applied.

There seems to be a conflict between the sort plugin that I'm using and zclip.  I don't know whether or not you've had any previous issues with mixitup by kunkalabs?

And I'm using chrome, latest flash, latest jquery.

**Comment by patricklodder** [comment]
@samayres1992 can you reproduce your issue over at jsfiddle.net so i can have a look at what's happening with your particular code? 

At a quick glance I see no immediate conflict between the two libraries, though I could imagine that if you have an element list with copy overlays getting repositioned by sorting, you might need to reposition the div containers with the actual swf overlay object accordingly, using the zclip Client `.reposition()` method at https://github.com/patricklodder/jquery-zclip/blob/master/jquery.zclip.js#L363
